language: java
jdk:
  - openjdk11
  
dist: xenial

arch:
  - amd64
  - ppc64le

addons:
  apt:
    packages:
     - ant 1.10.7

env:
  - MAVEN_OPTS="-Xmx4096m -XX:MaxPermSize=128m" HADOOP_VERSION="2.4.1"

sudo: false

cache:
  directories:
    - $HOME/.m2
