language: java
jdk:
  - openjdk11
  
dist: xenial

arch:
  - amd64
  - ppc64le

addons:
  apt:
    packages:
     - ant 1.10.7

env:
  - MAVEN_OPTS="-Xmx4096m -XX:MaxPermSize=128m" HADOOP_VERSION="2.4.1"

sudo: false

script:
    - mkdir -p build/debug
    - cd build/debug
    - cmake ../..
    - make 
    - cd build/debug
    - cmake ../..  
    - cd build/debug
    - ctest 
cache:
  directories:
    - $HOME/.m2
